# Makefile for Pblaze3 products

DRIVER_DIR := driver
TOOLS_DIR := tools

default:
	$(MAKE) -C $(DRIVER_DIR)
	$(MAKE) -C $(TOOLS_DIR)
clean:
	$(MAKE) -C $(DRIVER_DIR) clean
	$(MAKE) -C $(TOOLS_DIR) clean
install:
	$(MAKE) -C $(DRIVER_DIR) install
	$(MAKE) -C $(TOOLS_DIR) install
uninstall:
	$(MAKE) -C $(DRIVER_DIR) uninstall
	$(MAKE) -C $(TOOLS_DIR) uninstall


